[package]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
edition = "2018"
name = "designer"
version = "0.1.0"

[dependencies]
color-eyre = "*"
colored = "*"
derive_more = "*"
enumset = "*"
eyre = "*"
lazy_static = "*"
log = "*"
ordered-float = "*"
pretty_env_logger = "*"
radiate = "*"
rand = "*"
strum = "*"
strum_macros = "*"
syn = "=1.0.57"

[profile.release]
debug = 1 # line tables only
lto = false
