[package]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
edition = "2018"
name = "designer"
version = "0.1.0"

[workspace]
members = ["ga"]

[dependencies]
color-eyre = "*"
colored = "*"
derive_more = "*"
enumset = "*"
eyre = "*"
ga = {path = "./ga"}
lazy_static = "*"
log = "*"
ordered-float = "*"
pretty_env_logger = "*"
priority-queue = "*"
rand = "*"
rayon = "*"
serde = {version = "*", features = ["derive"]}
smallvec = "*"
structopt = "*"
strum = "*"
strum_macros = "*"
vec_map = "*"

[dev-dependencies]
criterion = {version = "*", features = ["real_blackbox"]}

[[bench]]
harness = false
name = "path"

[profile.release]
debug = 1 # line tables only
lto = false
