[package]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
edition = "2018"
name = "kbd"
version = "0.1.0"

[dependencies]
approx = "*"
color-eyre = "*"
derive_more = "*"
eyre = "*"
lazy_static = "*"
log = "*"
memega = {path = "../libs/memega"}
num_enum = "*"
pretty_env_logger = "*"
rand = "*"
rayon = "*"
serde = {version = "*", features = ["derive"]}
smallvec = "*"
structopt = "*"
strum = {version = "*", features = ["derive"]}
vec_map = "*"

[dev-dependencies]
criterion = {version = "*", features = ["real_blackbox"]}

[[bench]]
harness = false
name = "path"
